# Numpy All Important Functions

In [15]:
import numpy as np


# One-Dimensional array

In [16]:
a=np.array([1,2,3],dtype='int32')
print(f"The type of a is {type(a)} and the dimensions are:{a.ndim} and the size is:{a.nbytes} bytes")

The type of a is <class 'numpy.ndarray'> and the dimensions are:1 and the size is:12 bytes


## Two-Dimensional array

In [17]:
b=np.array([[1,2,3],[5,6,7.1],[7,8,9]])
print(f"The type of b is {type(b)} and the dimensions are:{b.ndim} and the shape is:{b.shape} and the size per item is:{b.itemsize} bytes")

The type of b is <class 'numpy.ndarray'> and the dimensions are:2 and the shape is:(3, 3) and the size per item is:8 bytes


- **Get a specific element**:  
  `array[r, c]` → Element at row `r`, column `c`
- **Get a specific row**:  
  `array[r, :]` → All columns from row `r`

- **Get a specific column**:  
  `array[:, c]` → All rows from column `c`

In [18]:
print(b[1,2])
b[1,2]=8.9
print(b[1,2])
print(b[1,:])

7.1
8.9
[5.  6.  8.9]


# Three-Dimensional Array

In [19]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(f"The dimensions of c are:{c.ndim} and the shape is:{c.shape} and the size per item is:{c.itemsize} bytes")
c

The dimensions of c are:3 and the shape is:(2, 2, 3) and the size per item is:8 bytes


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

- **Get a specific element**:  
  `array[block, row, column]` → Element at the given block, row, and column

- **Get a specific block**:  
  `array[block, :, :]` → All rows and columns from a specific block

- **Get a specific row from all blocks**:  
  `array[:, row, :]` → All blocks, specific row, all columns

- **Get a specific column from all blocks**:  
  `array[:, :, column]` → All blocks, all rows, specific column


In [20]:
print(c[1,0,0])
print(c[:,1,:])
c[:,1,:]=[[9,9,9],[8,8,8]]
print(c[:,1,:])

7
[[ 4  5  6]
 [10 11 12]]
[[9 9 9]
 [8 8 8]]


**Matrix Building**

In [21]:
print(np.zeros((3,2)))
print(np.ones((3,2)))
print(np.full((3,2),77))
print(np.full_like(a, 4)) #takes the size of already built array

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[77 77]
 [77 77]
 [77 77]]
[4 4 4]


**Matrix of random numbers**

In [22]:
print(np.random.rand(4,2))
print(np.random.randint(8,size=(2,2)))

[[0.23611429 0.79366468]
 [0.01030104 0.37719343]
 [0.92940115 0.44674233]
 [0.88955797 0.19982679]]
[[1 5]
 [3 5]]


**Identity matrix**

In [23]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Building matrix of your choice**

In [24]:
output=np.ones((5,5))
z=np.zeros((3,3))
z[1,1]=9
output[1:4,1:4]=z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Mathematical Operation**

In [25]:
d=np.array([1,2,3,4])
print(d+2)
print(d-2)
print(d*2)
print(d/2)
print(d**2)
print(np.sin(d))

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


**Linear Algebra**

In [26]:
m1=np.array([[1,2,3,4],[5,6,7,8]])
m2=np.array([[4,6,7],[2,5,8],[9,7,5],[2,0,5]])
#The number of columns in m1 to match the number of rows in m2
np.matmul(m1,m2)

array([[ 43,  37,  58],
       [111, 109, 158]])

In [27]:
# For determinant, use a square matrix
square_m = np.array([[1, 2],
                     [3, 4]])
print("Determinant:", np.linalg.det(square_m))

Determinant: -2.0000000000000004


**Statistics**

In [29]:
stats=np.array([[1,2,9],[4,5,6]])
print(np.min(stats,axis=1))
print(np.max(stats))
print(np.sum(stats))

[1 4]
9
27
