In [1]:
import numpy
numpy.__version__

'2.1.2'

In [2]:
import numpy as np

In [3]:
list1=[True,'0',9.0,8]
for item in list1:
    print(type(item))

<class 'bool'>
<class 'str'>
<class 'float'>
<class 'int'>


In [4]:
l = list(range(10))
a = np.array(l)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [7]:
x= np.arange(10)
x
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [8]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [16]:
x=np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [17]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [19]:
x=np.array([1,2,3])
y=np.array([3,6,8])
z=np.array([9,4,5])
np.concatenate([x,y,z])

array([1, 2, 3, 3, 6, 8, 9, 4, 5])

In [22]:
grid=np.array([[1,2,3],
               [4,5,6]])
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [3]:
x=np.array([1,2,3])
y=np.array([[4,5,6],
            [7,8,9]])
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
z=np.array([[99],
            [99]])
np.hstack([y,z])

array([[ 4,  5,  6, 99],
       [ 7,  8,  9, 99]])

In [7]:
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
%timeit compute_reciprocals(values)

16.5 μs ± 2.43 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [10]:
x=np.array([1,-4,-9,6])
np.absolute(x)

array([1, 4, 9, 6])

In [11]:
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [1]:
import numpy as np
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [3]:
np.count_nonzero(x<6)

8

In [5]:
np.sum(x<6,axis=1)

array([4, 2, 2])

In [6]:
np.any(x==6)

np.True_

In [7]:
np.all(x==0)

np.False_

In [8]:
import numpy as np
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [9]:
ind=[2,5,9]
x[ind]

array([14, 20, 74], dtype=int32)

In [10]:
x=np.array([4,5,1,3,2])
np.sort(x)

array([1, 2, 3, 4, 5])

In [11]:
np.argsort(x)

array([2, 4, 3, 0, 1])