In [1]:
import numpy as np


In [2]:
myarr=np.array([[2,3,4,5],[6,7,8,9]],np.int64)
type(myarr)

numpy.ndarray

In [3]:
myarr[0,1]

np.int64(3)

In [4]:
myarr.shape

(2, 4)

In [5]:
myarr[0,3]=45
print(myarr.size)
print(myarr)

8
[[ 2  3  4 45]
 [ 6  7  8  9]]


In [6]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
rng=np.arange(10)
print(type(rng))
print(rng)

<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


In [8]:
lspace=np.linspace(1,10,5) #It provide 5 equally spaced elements between 1 and 10 
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [9]:
emp=np.empty((2,5))
emp

array([[nan,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
ide=np.identity(10) #array of 10 by 10
print(np.shape(ide))
ide

(10, 10)


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Row, axis=1 & Column, axis=0

In [11]:
x=[[1,2,3],[4,5,6],[7,8,9]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
ar.sum(axis=0)

array([12, 15, 18])

In [13]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [14]:
ar.ndim

2

In [15]:
one=np.array([1,2,3,4,5,0])
print(one.argmax())
print(one.argmin())
print(one.argsort()) #it will give indexes of array to be sorted

4
5
[5 0 1 2 3 4]


In [16]:
ar1=np.array([[4,7,1],
              [7,4,3]])
ar2=np.array([[0,7,1],
              [2,9,3]])
print(ar1+ar2)
print(np.sqrt(ar))
print(ar.sum())
print(ar.max())
print(ar.min())

[[ 4 14  2]
 [ 9 13  6]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
45
9
1
